In [ ]:
import numpy as np

In [ ]:
a =[2,3,4,5]
a


In [ ]:
a = [[2,3,4],[4,5,6]]
a

In [ ]:
nparr = np.array(a)



In [ ]:
nparr.dtype

In [ ]:
# nparr2 = np.array([2,3,4,5],dtype=np.int32)
# nparr2 = np.array([2,3,4,5,"hello"]) # U21 ununified
# nparr2 = np.array([2,3,4,5,"hello"] , dtype=np.int128) # will give error
# nparr2 = np.array([2,3,4,5,"2"] , dtype=np.int128)  # will get error
nparr2 = np.array([2,3,4,5,2 ], dtype=np.int64)
nparr2.dtype

In [ ]:

# creating a numpy array

nparr = np.full((3,3),10) # creating a array of 3 * 3 with data as 10
ones = np.ones((3,3)) # creating a array of 3 * 3 with data as 1
zeros = np.zeros((3,3)) # creating a array of 3 * 3 with data as 0
print(nparr)
print(ones)
print(zeros)

In [ ]:
np.arange(10,105,5) # end is excluded

In [ ]:
line = np.linspace(10,105,10)
print(line)

In [ ]:
l1 = [1,2,3,4,4]
l2 = [4,5,6,4,10]

np1 = np.array(l1)
np2 = np.array(l2)
print(np1 * np2)
print(np1 )
print(np2)

In [ ]:
newarr= np.array([1,2,3])
newarr2= np.array([[1] ,[3]])
print(newarr + newarr2)

In [ ]:
np.sqrt(newarr)

# Rules of Broadcasting

Broadcasting follows a set of rules to determine the interaction between the two arrays:

1. **Dimension Compatibility**: Starting from the trailing dimensions, the dimensions of the arrays must either be the same, or one of them must be 1.
  
2. **Stretching**: If the sizes along a dimension are not the same, NumPy will try to stretch the array with size 1 along that dimension to match the other size.

3. **Result Shape**: The shape of the resulting array is the maximum size along each dimension from the input arrays.

### Scalar and One-dimensional Array


In [ ]:
arr = np.array([1, 2, 3])

res_arr = arr + 5

In [ ]:
res_arr


### Two-dimensional Array and One-dimensional Array



In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.ones((3))

print(arr1d)

In [ ]:
arr2d + arr1d



### Broadcasting Two Arrays with Different Shapes



In [ ]:
A = np.array([[1, 2], [3, 4], [5, 6]])

A.shape

In [ ]:
B = np.array([1, 2,])

In [ ]:
A + B


## Practical Applications

1. **Data Normalization**: Broadcasting can be used to normalize datasets by subtracting the mean and dividing by the standard deviation.
  
2. **Image Manipulation**: You can use broadcasting to apply filters or adjustments to RGB channels in images.

3. **Mathematical Modeling**: In simulations or mathematical models, broadcasting can simplify the code and make it more efficient.

## Caveats and Limitations

1. **Implicitness**: Broadcasting can make code less explicit, which may lead to bugs if you're not careful about array shapes.

2. **Memory Efficiency**: While broadcasting saves memory by avoiding explicit replication of data, it's still possible to run into memory issues with very large arrays.


#  Indexing and Slicing - Accessing Array Elements in NumPy

## Introduction


---

## Part 1: Basic Indexing









In [ ]:
import numpy as np

In [ ]:
exam_scores = np.array([90, 85, 77, 92])

In [ ]:
print("fisrt statudne scre is " , exam_scores[0])

fisrt statudne scre is  90


## Part 2: Multidimensional Indexing
    - Accessing elements in 2D and 3D arrays.
    - Using row and column indices.


In [ ]:
sales_data = np.array([
    [[200, 222], 220, 250],
    [210, 230, 275],
    [190, 205, 235]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 3) + inhomogeneous part.

In [ ]:
sales_data[0, 0][1]

NameError: name 'sales_data' is not defined

## Part 3: Basic Slicing
    - How to slice arrays to get subarrays.
    - Using the `start:stop:step` notation.


In [ ]:
monthly_revenue = np.array([200, 220, 250, 275, 344, 350, 320, 400, 420, 450, 450])

In [ ]:
monthly_revenue[::-1]

## Part 4: Advanced Slicing Techniques
    - Using boolean arrays for indexing.
    - Combining slicing with conditional statements.


In [ ]:
avg = np.mean(monthly_revenue)
avg

334.45454545454544

In [ ]:
monthly_revenue > avg

array([False, False, False, False,  True,  True, False,  True,  True,
        True,  True])

In [ ]:
monthly_revenue[monthly_revenue > avg] # conditional asking

array([344, 350, 400, 420, 450, 450])

## Part 5: Important Caveats and Best Practices
    - Mention that slices are views, not copies.
    - The importance of being aware of data types when slicing and indexing.


In [ ]:
monthly_revenue_ab_avg =  monthly_revenue[monthly_revenue > avg] # conditional asking

In [ ]:
monthly_revenue_ab_avg

array([344, 350, 400, 420, 450, 450])

# Mini Project: 1D Slicing and Indexing with NumPy

## Objective

In this mini-project, you will practice 1D slicing and indexing techniques using NumPy. We'll work on a dataset that represents monthly sales data for a retail store and perform various data manipulation tasks.

## Dataset

Let's assume we have a 1D NumPy array that represents the monthly sales for a retail store for one year, in thousands of dollars.



In [ ]:
import numpy as np

monthly_sales = np.array([200, 220, 250, 275, 300, 320, 350, 370, 400, 420, 450, 475])


## Tasks

### Task 1: Basic Indexing

1. Access and print the sales data for January (the first month).
2. Access and print the sales data for December (the last month).








In [ ]:
monthly_sales[0]
monthly_sales[-1]

475

### Task 2: Access Quarterly Data

1. Extract and print the sales data for each quarter (Q1, Q2, Q3, and Q4).

In [ ]:
q1s = monthly_sales[0:3]
q2s = monthly_sales[3:6]
q3s = monthly_sales[6:9]
q4s = monthly_sales[9:]
print(q1s)
print(q2s)
print(q3s)
print(q4s)

[200 220 250]
[275 300 320]
[350 370 400]
[420 450 475]



### Task 3: Modify Sales Data

1. Assume that there was an error in the data entry for the month of April. The correct sales figure is $280,000. Update this value in the array.
2. Print the updated array to confirm the change.

In [ ]:
monthly_sales[3] = 280
monthly_sales

array([200, 220, 250, 280, 300, 320, 350, 370, 400, 420, 450, 475])

### Task 4: Summer Sales

1. Extract and print the sales data for the summer months (June, July, August).
2. Calculate and print the average sales for the summer months.

In [ ]:
# summer_month = np.array([monthly_sales[5],monthly_sales[6],monthly_sales[7]])
summer_month = monthly_sales[5:8]
print(summer_month)
avg = np.mean(summer_month)
print(avg)

[320 350 370]
346.6666666666667


### Task 5: Above Average Months

1. Calculate the average monthly sales for the entire year.
2. Identify and print the months where the sales were above average.

In [ ]:
avgall = np.mean(monthly_sales)
print(avgall)
print(monthly_sales[monthly_sales > avgall])

336.25
[350 370 400 420 450 475]


# Python Loops vs Vectorization in NumPy

## Introduction

---

## Part 1: Understanding Python Loops







In [ ]:
daily_users = [200, 220, 250, 275]

avg_users = 0
for e in daily_users:
  avg_users += e

print(avg_users / len(daily_users))

236.25


## Part 2: Introduction to Vectorization
  - What vectorization is and why it's important.
  - Brief explanation of how NumPy uses vectorized operations.


In [ ]:
import numpy as np


## Part 3: Performance Comparison



In [ ]:
large_arr = np.random.randint(1,100,size=10004000)

In [ ]:
import time

start_time = time.time()
avg_users = 0
for e in large_arr:
  avg_users += e
print(avg_users / len(large_arr))
end_time = time.time()
print(end_time - start_time)


50.009082666933224
1.66817307472229


In [ ]:
start_time = time.time()
avg = np.mean(large_arr)
print(avg)
end_time = time.time()
print(end_time - start_time)


50.009082666933224
0.019052505493164062


## Part 4: When to Use Loops and When to Use Vectorization


In [ ]:
filtered_user = []

for user_m in large_arr:
   if user_m > 20 and user_m % 2 ==0:
    filtered_user.append(user_m)

print(filtered_user)

Output hidden; open in https://colab.research.google.com to view.

# Exercise: Vectorize a Given Python Loop

## Objective

In this exercise, you'll practice converting a Python loop that performs a mathematical operation into a vectorized version using NumPy. By doing so, you'll learn to write more efficient and cleaner code.

## Scenario

Imagine you're working with a dataset containing the monthly sales data for a retail business. You want to apply a 10% discount to each monthly sales figure to calculate the new sales numbers.



## Task 1: Using Python Loop

1. Create a list called `monthly_sales` containing 12 integers, each representing the sales for a month.
2. Initialize an empty list called `discounted_sales`.
3. Loop through each value in `monthly_sales`, apply a 10% discount, and append the result to `discounted_sales`.


In [ ]:
monthly_sales = np.random.randint(1,100,size=12)
print(monthly_sales)
discounted_sales = []

for e in monthly_sales:
  discounted_sales.append(e * 9)

print(discounted_sales)


[23 80 49  4  9 17 86  2 90 65 85  5]
[207, 720, 441, 36, 81, 153, 774, 18, 810, 585, 765, 45]



## Task 2: Using NumPy Vectorization

### Instructions

1. Convert the `monthly_sales` list into a NumPy array.
2. Use NumPy's vectorized operations to apply a 10% discount to each value.
3. Store the result in a new NumPy array called `discounted_sales_np`.


In [ ]:
discounted_sales_np = monthly_sales * 0.9
print(discounted_sales_np)

[20.7 72.  44.1  3.6  8.1 15.3 77.4  1.8 81.  58.5 76.5  4.5]


# Universal Functions - The Power of UFuncs in NumPy

## Introduction



## Part 1: What are UFuncs?
    - Definition and characteristics of UFuncs.
    - UFuncs allow for element-wise operations on arrays.













In [ ]:
import numpy as np
product_prices = np.array([20,25,34,34,345,456,34,])

In [ ]:
np.sqrt(product_prices)

array([ 4.47213595,  5.        ,  5.83095189,  5.83095189, 18.57417562,
       21.3541565 ,  5.83095189])

## Part 2: Basic UFuncs for Arithmetic Operations
    - Common arithmetic operations like addition, subtraction, multiplication, and division.


In [ ]:
x1 = np.array([3,4,54,5,4,5,4,4])
x2 = np.array([3,6,7,7,4,6,4,5])
np.add(x1,x2)
np.subtract(x1,x2)

array([ 0, -2, 47, -2,  0, -1,  0, -1])


## Part 3: Trigonometric and Logarithmic UFuncs
    - Trigonometric functions like `np.sin`, `np.cos`.
    - Logarithmic functions like `np.log`, `np.exp`.

In [ ]:
principle = 1000
rate = 0.08
years = np.array([1,2,3,4,5])

In [ ]:
ci = np.multiply( principle , np.exp(rate * years))
ci

array([1083.28706767, 1173.51087099, 1271.24915032, 1377.12776434,
       1491.82469764])

## Part 4: Comparison and Logical UFuncs
    - Comparison UFuncs like `np.greater`, `np.less_equal`.
    - Logical UFuncs like `np.logical_and`, `np.logical_or`.


In [ ]:
revenue = np.array( [4000, 4500 , 4000] )
expenses = np. array( [2000, 1500, 2500] )

In [ ]:
# expenses[np.less_equal(expenses , 2000)]
# expenses[expenses <= 2000]

## Part 5: Custom UFuncs
    - Creating custom UFuncs using `np.vectorize`.


In [ ]:
def calculate_nps(score):
  if score >= 90:
    return 'promoter'
  elif score >= 60:
    return 'pasitive'
  else:
    return "Detractor"

In [ ]:
bps_func = np.vectorize(calculate_nps)

In [ ]:
scores = np.array([120,234,645,23,23,70,80])

In [ ]:
bps_func(scores)

array(['promoter', 'promoter', 'promoter', 'Detractor', 'Detractor',
       'pasitive', 'pasitive'], dtype='<U9')

# Conditional Selection - Choosing with Conditions in NumPy

## Introduction

---

## Part 1: Basic Conditional Selection
- **Bullet Points**:
    - Introduction to the `np.where` function for basic conditional operations.
    - Real-world Example: Determining which employees are eligible for a bonus based on their performance scores.




In [ ]:
import numpy as np
scores = np.array([85, 90, 78, 92, 88])

In [ ]:
eligibility = np.where(scores > 80, "yes ur " , "NO")
eligibility

array(['yes ur ', 'yes ur ', 'yes ur ', 'NO', 'NO', 'NO', 'NO'],
      dtype='<U7')

array(['No', 'Yes', 'No', 'Yes', 'Yes'], dtype='<U3')

## Part 2: Multiple Conditions
    - Using logical operators like `&` (and), `|` (or) to combine conditions.


In [ ]:
eligibility = np.where((scores < 80) | (scores > 90), "yes ur " , "NO")
eligibility

array(['yes ur ', 'yes ur ', 'yes ur ', 'yes ur ', 'yes ur ', 'yes ur ',
       'NO'], dtype='<U7')

## Part 3: Filtering Arrays
    - Using boolean indexing to filter arrays based on conditions.


In [ ]:
scores[(scores < 87) | (scores > 90)]

array([85, 78, 92])

## Part 4: Nested Conditions
    - Using nested `np.where` for more complex conditional logic.


In [ ]:
np.where(scores < 80 , "Yes", np.where(scores > 90 , "Yes", "No"))

array(['No', 'No', 'Yes', 'Yes', 'No'], dtype='<U3')

# Conditional Selection - Choosing with Conditions in NumPy

## Introduction

---

## Part 1: Basic Conditional Selection
- **Bullet Points**:
    - Introduction to the `np.where` function for basic conditional operations.
    - Real-world Example: Determining which employees are eligible for a bonus based on their performance scores.




In [ ]:
import numpy as np
scores = np.array([85, 90, 78, 92, 88])

In [ ]:
eligibility = np.where(scores > 85, "Yes", "No")

In [ ]:
eligibility

array(['No', 'Yes', 'No', 'Yes', 'Yes'], dtype='<U3')

## Part 2: Multiple Conditions
    - Using logical operators like `&` (and), `|` (or) to combine conditions.


In [ ]:
eligibility = np.where((scores < 87) & (scores > 80) | (scores > 90) , "Yes", "No")
eligibility

array(['Yes', 'No', 'No', 'Yes', 'No'], dtype='<U3')

## Part 3: Filtering Arrays
    - Using boolean indexing to filter arrays based on conditions.


In [ ]:
scores[(scores < 87) | (scores > 90)]

array([85, 78, 92])

## Part 4: Nested Conditions
    - Using nested `np.where` for more complex conditional logic.


In [ ]:
np.where(scores < 80 , "Yes", np.where(scores > 90 , "Yes", "No"))

array(['No', 'No', 'Yes', 'Yes', 'No'], dtype='<U3')

# Reshaping Arrays - Changing Dimensions and Size in NumPy

## Introduction

---

## Part 1: The `reshape` Method
    - Introduction to the `np.reshape` function for changing array dimensions.



In [3]:
import numpy as np

data = np.random.randint(10, 100, 100)

In [12]:
# data.reshape(25,4)
data.reshape(10,10)

array([[65, 88, 32, 32, 21, 32, 16, 84, 43, 94],
       [75, 97, 39, 40, 14, 17, 74, 58, 60, 79],
       [74, 84, 91, 65, 26, 47, 65, 61, 57, 50],
       [89, 19, 98, 83, 60, 62, 52, 47, 42, 43],
       [79, 67, 72, 14, 51, 95, 15, 35, 28, 29],
       [43, 58, 19, 43, 43, 69, 38, 95, 61, 18],
       [58, 80, 22, 46, 24, 66, 72, 82, 47, 52],
       [80, 26, 20, 62, 46, 55, 95, 80, 83, 48],
       [27, 26, 11, 30, 52, 11, 47, 89, 85, 17],
       [22, 95, 49, 77, 12, 80, 90, 56, 57, 24]])

## Part 2: Flattening Arrays
    - Using `ravel()` and `flatten()` to convert multi-dimensional arrays to 1D arrays.


In [16]:
data2 = np.random.randint(10, 100,25)

In [18]:
data2.shape

(25,)

In [21]:
data2.flatten() # retrun a copy of the flattered array
data2.ravel()

array([58, 32, 35, 67, 62, 84, 20, 12, 74, 93, 89, 77, 54, 24, 17, 35, 62,
       39, 86, 94, 30, 16, 85, 17, 41])

In [26]:

 # Transposing array
data_T = np.random.randint(10,100,20).reshape(2,10)
data_T

array([[25, 48, 37, 22, 43, 18, 74, 34, 99, 58],
       [64, 44, 37, 93, 68, 75, 33, 99, 20, 90]])

## Part 4: Resizing Arrays
    - Using `np.resize` to change the size of an array.



In [25]:
np.resize(data_T, (5, 4))

array([[24, 58, 16, 21, 26, 16, 53, 50, 88, 34],
       [43, 14, 87, 18, 92, 87, 14, 79, 25, 72],
       [24, 58, 16, 21, 26, 16, 53, 50, 88, 34],
       [43, 14, 87, 18, 92, 87, 14, 79, 25, 72],
       [24, 58, 16, 21, 26, 16, 53, 50, 88, 34]])

In [27]:
datat1 = np.array([2,4,5,4,5,5,7])
datat2 = np.array([2,4,5,44,5,3,34,347])

In [28]:
np.concatenate([datat1,datat2])

array([  2,   4,   5,   4,   5,   5,   7,   2,   4,   5,  44,   5,   3,
        34, 347])

In [32]:
np.hstack([datat1,datat2])

array([  2,   4,   5,   4,   5,   5,   7,   2,   4,   5,  44,   5,   3,
        34, 347])

In [31]:
np.vstack([datat1,datat2])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 7 and the array at index 1 has size 8

TypeError: split() missing 1 required positional argument: 'indices_or_sections'

# Handling Missing Values Using NumPy

## Introduction


## Part 1: Understanding Missing Values
    - Types of missing values: completely missing, partially missing, or incorrectly entered.
    - Common reasons for missing values: data entry errors, unavailability of information, etc.


In [35]:
import numpy as np

customer_data = np.array([100, 150, np.nan, 200, 175])

In [36]:
missing_values = np.isnan(customer_data)
missing_values

array([False, False,  True, False, False])

## Part 2: Identifying Missing Values in NumPy
    - Using `np.isnan()` to identify missing values.
    - Counting the number of missing values in an array.



In [ ]:
print("we have this many missing values ", np.sum(missing_values))

we have this many missing values  1


## Part 3: Replacing Missing Values
    - Using `np.nan_to_num()` to replace missing values with zero.
    - Replacing missing values with mean, median, or a specific value using `np.nanmean()` and `np.nanmedian()`.



In [39]:
zero_filles = np.nan_to_num(customer_data)

array([100., 150.,   0., 200., 175.])

In [42]:
data_mean = np.nanmean(customer_data)
data_mean_fill = np.where(np.isnan(customer_data), data_mean, customer_data)
data_mean_fill
np.nanmedian(customer_data)

162.5

## Part 4: Deleting Missing Values
    - Deleting rows with missing values using `np.isnan()` and array slicing.
    - When to delete data: caution about losing information.



In [43]:
data_without_nan = customer_data[~np.isnan(customer_data)]
data_without_nan

array([100., 150., 200., 175.])

## Part 5: Forward and Backward Filling of Missing Values
    - Using methods to fill missing values based on neighboring elements.

In [47]:
copy_of_cd = np.copy(customer_data)
mask = np.isnan(copy_of_cd)
copy_of_cd[mask] = np.roll(copy_of_cd , shift=-1)[mask]
copy_of_cd

array([100., 150., 200., 200., 175.])

# File Handling - Saving and Loading NumPy Arrays

## Introduction


---

## Part 1: Saving Arrays with `np.save` and `np.savez`
    - Introduction to the `np.save` function for saving single arrays.
    - Use of `np.savez` for saving multiple arrays.








In [48]:
import numpy as np

age = np.array([18, 25, 33, 44, 22, 45])

In [49]:
np.save("age.npy", age)

## Part 2: Loading Arrays with `np.load`
    - Using the `np.load` function to load saved arrays.



In [50]:
loaded_age = np.load("age.npy")

In [51]:
loaded_age

array([18, 25, 33, 44, 22, 45])

## Part 3: Saving Text Files with `np.savetxt`
    - Introduction to `np.savetxt` for saving arrays as text files.

In [52]:
np.savetxt("age.txt", loaded_age, delimiter=",")

## Part 4: Loading Text Files with `np.loadtxt`
    - Using `np.loadtxt` to read text files and create arrays.



In [53]:
new_age = np.loadtxt("age.txt", delimiter=",")
new_age

array([18., 25., 33., 44., 22., 45.])


## Part 5: Additional Options and Parameters
    - Discussion of additional parameters like `delimiter`, `skiprows`, and `usecols`.

